<?php

$son = '$id, $ver, $estate, $lodgeAddress, $lodgeUnitRepository, $landlord, $operator, $validTo, $name, $leaseType, $houseTypeRoom, $houseTypeHall, $houseTypeToilet, $houseTypeKitchen, $houseTypeBalcony, $state, $intro, $roomsNum, $area, $guestNum, $liveTogether, $bedroomNum, $isCook, $toiletNum, $privateToiletNum, $tv, $wirelessnetwork, $wirednetwork, $aircondition, $icebox, $drinking, $washer, $heater, $shower, $hotbathtub, $kitchen, $brush, $soap, $supermarket, $bank, $toiletries, $slippers, $towel, $pet, $smoke, $meet, $security, $elevator, $accesssys, $parkingspace, $toiletPaper, $addTenant, $addTenantNum, $addTenantPrice, $addTenantTips, $sheetChange, $cashpledge, $mindays, $maxdays, $foreigner, $cancelRule_P, $cancelRule_N, $cancelRule_A, $cancelRule_B, $cancelRule_Req, $useRule, $bizDistrict, $mainImageId, $createTime, $lastUpdateTime, $serviceIntro, $roominnerIntro, $locationIntro, $stationairportIntro, $trafficIntro, $aroundVillageIntro, $cbdIntro, $viewspotIntro, $shoppingIntro, $entertainmentIntro, $educationIntro, $medicalIntro, $cashPledgeOnLine,$addtionalPrice,$hiddenTips,$lock,$lockAssignTime,$createType,$currency,$isSupportIm,$cleanFee,$suitableForChildren,$suitableForOldPeople,$suitableForDisabledPeople';
$fa = '$id, $ver, $estate, $lodgeAddress, $lodgeUnitRepository, $landlord, $operator, $validTo, $name, $leaseType, $houseTypeRoom, $houseTypeHall, $houseTypeToilet, $houseTypeKitchen, $houseTypeBalcony, $state, $intro, $roomsNum, $area, $guestNum, $liveTogether, $bedroomNum, $isCook, $toiletNum, $privateToiletNum, $tv, $wirelessnetwork, $wirednetwork, $aircondition, $icebox, $drinking, $washer, $heater, $shower, $hotbathtub, $kitchen, $brush, $soap, $supermarket, $bank, $toiletries, $slippers, $towel, $pet, $smoke, $meet, $security, $elevator, $accesssys, $parkingspace, $toiletPaper, $addTenant, $addTenantNum, $addTenantPrice, $addTenantTips, $sheetChange, $cashpledge, $mindays, $maxdays, $foreigner, $cancelRule_P, $cancelRule_N, $cancelRule_A, $cancelRule_B, $cancelRule_Req, $useRule, $bizDistrict, $mainImageId, $createTime, $lastUpdateTime, $serviceIntro, $roominnerIntro, $locationIntro, $stationairportIntro, $trafficIntro, $aroundVillageIntro, $cbdIntro, $viewspotIntro, $shoppingIntro, $entertainmentIntro, $educationIntro, $medicalIntro, $cashPledgeOnLine,$addtionalPrice,$hiddenTips,$lock,$lockAssignTime,$createType,$currency,$isSupportIm,$cleanFee,$suitableForChildren,$suitableForOldPeople,$suitableForDisabledPeople';
$father = '$id, $ver, $estate, $lodgeAddress, $landlord, $operator, $validTo, $name, $address, $longitude, $latitude, $leaseType, $houseTypeRoom, $houseTypeHall, $houseTypeToilet, $houseTypeKitchen, $houseTypeBalcony, $state, $intro, $roomsNum, $area, $guestNum, $liveTogether, $bedroomNum, $isCook, $toiletNum, $privateToiletNum, $tv, $wirelessnetwork, $wirednetwork, $aircondition, $icebox, $drinking, $washer, $heater, $shower, $hotbathtub, $kitchen, $brush, $soap, $supermarket, $bank, $toiletries, $slippers, $towel, $pet, $smoke, $meet, $security, $elevator, $accesssys, $parkingspace, $toiletPaper, $addTenant, $addTenantTips, $sheetChange, $cashpledge, $mindays, $maxdays, $foreigner, $cancelRule_P, $cancelRule_N, $cancelRule_A, $cancelRule_B, $cancelRule_Req, $useRule, $bizDistrict, $mainImageId, $createTime, $lastUpdateTime, $serviceIntro, $roominnerIntro, $locationIntro, $stationairportIntro, $trafficIntro, $aroundVillageIntro, $cbdIntro, $viewspotIntro, $shoppingIntro, $entertainmentIntro, $educationIntro, $medicalIntro, $lastAuditVer,$lastAuditSummary,$cashPledgeOnLine,$addtionalPrice,$hiddenTips,$suitableForChildren,$suitableForOldPeople,$suitableForDisabledPeople';
$audit = '$id, $ver, $estate, $lodgeUnitRepository, $landlord, $operator, $validTo, $name, $lodgeAddressAuditMirror, $leaseType, $houseTypeRoom, $houseTypeHall, $houseTypeToilet, $houseTypeKitchen, $houseTypeBalcony, $intro, $roomsNum, $area, $guestNum, $liveTogether, $bedroomNum, $isCook, $toiletNum, $privateToiletNum, $tv, $wirelessnetwork, $wirednetwork, $aircondition, $icebox, $drinking, $washer, $heater, $shower, $hotbathtub, $kitchen, $brush, $soap, $supermarket, $bank, $toiletries, $slippers, $towel, $pet, $smoke, $meet, $security, $elevator, $accesssys, $parkingspace, $toiletPaper, $addTenant, $addTenantNum, $addTenantPrice, $addTenantTips, $sheetChange, $cashpledge, $mindays, $maxdays, $foreigner, $cancelRule_P, $cancelRule_N, $cancelRule_A, $cancelRule_B, $cancelRule_Req, $useRule, $bizDistrict, $mainImageId, $createTime, $lastUpdateTime, $serviceIntro, $roominnerIntro, $locationIntro, $stationairportIntro, $trafficIntro, $aroundVillageIntro, $cbdIntro, $viewspotIntro, $shoppingIntro, $entertainmentIntro, $educationIntro, $medicalIntro, $cashPledgeOnLine,$addtionalPrice,$hiddenTips,$needAudit,$editSummary=null,$currency = CurrencyEnum::CNY,$cleanFee,$suitableForChildren,$suitableForOldPeople,$suitableForDisabledPeople';
$respon = '$id, $ver, $estate, $lodgeAddressRepository, $lodgeUnitAuditMirror, $lodgeUnit, $landlord, $operator, $validTo, $name, $leaseType, $houseTypeRoom, $houseTypeHall, $houseTypeToilet, $houseTypeKitchen, $houseTypeBalcony, $intro, $roomsNum, $area, $guestNum, $liveTogether, $bedroomNum, $isCook, $toiletNum, $privateToiletNum, $tv, $wirelessnetwork, $wirednetwork, $aircondition, $icebox, $drinking, $washer, $heater, $shower, $hotbathtub, $kitchen, $brush, $soap, $supermarket, $bank, $toiletries, $slippers, $towel, $pet, $smoke, $meet, $security, $elevator, $accesssys, $parkingspace, $toiletPaper, $addTenant, $addTenantNum, $addTenantPrice, $addTenantTips, $sheetChange, $cashpledge, $mindays, $maxdays, $foreigner, $cancelRule_P, $cancelRule_N, $cancelRule_A, $cancelRule_B, $cancelRule_Req, $useRule, $bizDistrict, $mainImageId, $createTime, $lastUpdateTime, $serviceIntro, $roominnerIntro, $locationIntro, $stationairportIntro, $trafficIntro, $aroundVillageIntro, $cbdIntro, $viewspotIntro, $shoppingIntro, $entertainmentIntro, $educationIntro, $medicalIntro, $cashPledgeOnLine,$addtionalPrice,$hiddenTips,$offLineByRake,$lodgeUnitId,$editSummary=null,$currency=CurrencyEnum::CNY,$cleanFee,$isEditing,$suitableForChildren,$suitableForOldPeople,$suitableForDisabledPeople,$bookFlow=null';
echo count(explode(',', $son)) . "\n";
echo count(explode(',', $father)) . "\n";
echo count(explode(',', $audit)) . "\n";
echo count(explode(',', $respon)) . "\n";


